//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grade_Calculator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>90</string>
  <string>85</string>
  <string>80</string>
  <string>70</string>
  <string>60</string>
  <string>55</string>
  <string>50</string>
  <string>40</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FirstRanges {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FirstRanges"]));
            }
            set {
                this["FirstRanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>100</string>
  <string>90</string>
  <string>85</string>
  <string>80</string>
  <string>70</string>
  <string>60</string>
  <string>55</string>
  <string>50</string>
  <string>40</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LastRanges {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastRanges"]));
            }
            set {
                this["LastRanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>AA</string>
  <string>BA</string>
  <string>BB</string>
  <string>CB</string>
  <string>CC</string>
  <string>DC</string>
  <string>DD</string>
  <string>FD</string>
  <string>FF</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LetterGrades {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LetterGrades"]));
            }
            set {
                this["LetterGrades"] = value;
            }
        }
    }
}
